// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kuibafrgujpjtrjuctee.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1aWJhZnJndWpwanRyanVjdGVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0MzA2NTEsImV4cCI6MjA2NTAwNjY1MX0.Pdv13VJtHmwsBfKIel-9D8_2u4jIJ_UxFCUYyJq3Mac";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);